app/modules/dashboard/controllers/BannerNewsEventChannelController.php
<?php

namespace app\modules\dashboard\controllers;
use app\models\AdvertismentNeChannel;
use Yii;
class BannerNewsEventChannelController extends \yii\web\Controller
{
    public function actionIndex()
    {
      $breadcrumb = [
        [
          'page' => 'Advertisment News Event Page & Channel Page',
          'url' => '#',
          'current' => true
        ]
      ];

      return $this->render('index',[
        'breadcrumb' => $breadcrumb
      ]);
    }

    public function actionChange(){
      $this->layout = false;
      $id = Yii::$app->request->post('id');
      $data = AdvertismentNeChannel::findOne($id);
      return $this->render('change',['data'=>$data]);
    }

    public function actionInsert(){
      $model = AdvertismentNeChannel::findOne(Yii::$app->request->post('id'));
      $model->link = Yii::$app->request->post('link');
      if(isset($_FILES['banner']['name']) and $_FILES['banner']['name'] != ''){
        $file_name = $_FILES['banner']['name'];
        $file_tmp =$_FILES['banner']['tmp_name'];
        $tmp = explode('.', $file_name);
        $file_ext = end($tmp);
        $newfilename = md5(date('Y-m-d H:i:s')) .'.'. $file_ext;

        move_uploaded_file($file_tmp,"media/advertisment/".$newfilename);
        $model->image = $newfilename;
      }
      $model->expired = Yii::$app->request->post('expired') . ' 01:00:00';
      $model->save();
    }


}

app/modules/dashboard/views/banner-news-event-channel/change.php
<form id="change-adv-ne-channel">
  <input type="hidden" name="id" value="<?= $data->id ?>">
  <div class="form-group">
    <label for="">Link <span class="note">* exp <?= Yii::$app->params['base_url'] ?></span></label>
    <input type="text" class="form-control" name="link" value="<?= $data->link ?>">
  </div>
  <div class="form-group">
    <label for="">Expired</label>
    <input type="text" class="form-control datenow" readonly name="expired"  value="">
  </div>
  <div class="form-group">
    <label for="">Image  <span class="note">* image size must be 800px X 800px</span></label>
    <input type="file" name="image" class="setpreview" value="">
  </div>
  <div class="form-group">
    <?php if($data->image == ''){ ?>
      <img class="getpreview" src="<?= Yii::$app->params['base_url'] ?>demos/800x800.png" alt="">
    <?php }else{ ?>
      <img class="getpreview"  src="<?= Yii::$app->params['base_url'] ?>media/advertisment/<?= $data->image ?>" alt="">
    <?php } ?>
  </div>
  <input type="hidden" id="ri" value="<?= $data->image ?>">
  <div class="form-group">
    <button type="submit" class="btn btn-primary" name="button">Save</button>
  </div>
</form>

<style media="screen">
  #change-adv-ne-channel img{
    width: 200px
  }
  .note{
    font-size: 11px;
    color:red
  }
</style>
<script type="text/javascript">

function readThis(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('.getpreview').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$(".setpreview").change(function(){
    readURL(this);
});


$('#change-adv-ne-channel').validate({
  rules : {
    image : {
      required : function(){
        return $("#ri").val() == '';
      }
    },
    link : {
      url : true
    },
    expired : {
      required : true
    }
  },
  messages : {
    image : {
      required : 'please choose the image'
    },
    link : {
      url : 'please fill the right URL'
    },
    expired : {
      required : 'please fill the expired date'
    }
  },
  submitHandler : function(data){

    $('#change-adv-ne-channel button').prop('disabled',true).html('saving ...');
    var kuy = $('#change-adv-ne-channel')[0];
    var formData = new FormData(kuy);

    formData.append('banner', $('#change-adv-ne-channel input[type=file]')[0].files[0]);
    formData.append('_csrf', $('#gils').val());

    $.ajax({
      url :  '<?= Yii::$app->params['base_url'] ?>dashboard/'+ 'banner-news-event-channel/insert',
      type : 'POST',
      contentType: false,
      cache: false,
      processData:false,
      data : formData,
      success : function(data){
        window.location = base + 'banner-news-event-channel';
      }
    });

    return false;
  }
});

$( ".datenow" ).datepicker({
changeMonth: true,
changeYear: true,
dateFormat: 'yy-mm-dd',
minDate : 1
});
</script>

app/modules/dashboard/views/banner-news-event-channel/index.php
<?php

use app\helper\Helper;


/* @var $this yii\web\View */
/* @var $searchModel app\modules\dashboard\models\Search */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Data';
$this->params['breadcrumbs'][] = $this->title;
?>

<div id="content">
  <?= Helper::breadcrumb($breadcrumb); ?>
  <div class="container-fluid">
    <div class="page-index wrapindex">

        <div class="row">
          <div class="col-md-6">
            <h4 class="text-center">Advertisment News & Event Page</h4>
            <div class="item-adv">
              <div class="wrap-img">
                <?php if(Helper::getNeChannel(1)->image == ''){ ?>
                  <img  src="<?= Yii::$app->params['base_url'] ?>demos/800x800.png" alt="">
                <?php }else{ ?>
                  <img  src="<?= Yii::$app->params['base_url'] ?>media/advertisment/<?= Helper::getNeChannel(1)->image ?>" alt="">
                <?php } ?>
                <div class="change" data-id="1">
                  <p>Change</p>
                </div>
              </div>
            </div>


            <div class="item-adv">
              <div class="wrap-img">
                <?php if(Helper::getNeChannel(2)->image == ''){ ?>
                  <img  src="<?= Yii::$app->params['base_url'] ?>demos/800x800.png" alt="">
                <?php }else{ ?>
                  <img  src="<?= Yii::$app->params['base_url'] ?>media/advertisment/<?= Helper::getNeChannel(2)->image ?>" alt="">
                <?php } ?>
                <div class="change" data-id="2">
                  <p>Change</p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <h4 class="text-center">Advertisment Channel Page</h4>

            <div class="item-adv">
              <div class="wrap-img">

                <?php if(Helper::getNeChannel(3)->image != '' and Helper::getNeChannel(3)->expired >= date('Y-m-d H:i:s')){ ?>
                  <img  src="<?= Yii::$app->params['base_url'] ?>media/advertisment/<?= Helper::getNeChannel(3)->image ?>" alt="">
                <?php }else{ ?>
                  <img  src="<?= Yii::$app->params['base_url'] ?>demos/800x800.png" alt="">

                <?php } ?>
                <div class="change" data-id="3">
                  <p>Change</p>
                </div>
              </div>
            </div>

            <div class="item-adv">
              <div class="wrap-img">
                <?php if(Helper::getNeChannel(4)->image == ''){ ?>
                  <img  src="<?= Yii::$app->params['base_url'] ?>demos/800x800.png" alt="">
                <?php }else{ ?>
                  <img  src="<?= Yii::$app->params['base_url'] ?>media/advertisment/<?= Helper::getNeChannel(4)->image ?>" alt="">
                <?php } ?>
                <div class="change" data-id="4">
                  <p>Change</p>
                </div>
              </div>
            </div>
          </div>
        </div>

    </div>

  </div>
</div>

<style media="screen">
  .item-adv{
    text-align: center;
    margin-top: 20px;
  }
  .item-adv .wrap-img{
    width: 250px;
    height: 250px;
    margin: auto;
    position: relative;
  }
  .item-adv img{
    width: 100%;
    height: 250px;
    margin: auto;
  }
  .item-adv .change{
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.5);
    border:3px dashed #fff;
    cursor: pointer;
    display: none
  }
  .item-adv .wrap-img:hover .change{
    display: block
  }
  .item-adv .change p{
    position: absolute;
    left: 0;
    top:45%;
    width: 100%;
    color:#fff;
    text-transform: uppercase;
letter-spacing: 6px;
font-size: 20px;
  }
</style>