app/modules/dashboard/controllers/BankController.php
<?php

namespace app\modules\dashboard\controllers;
use Yii;
use app\models\Bank;

class BankController extends \yii\web\Controller
{
    public function actionIndex()
    {
      $breadcrumb = [
        [
          'page' => 'Bank',
          'url' => '#',
          'current' => true
        ]
      ];

      $banks = Bank::find()->andWhere(['is_delete'=>0])->all();

      return $this->render('index',[
        'breadcrumb' => $breadcrumb,
        'banks' => $banks
      ]);
    }

    public function actionFormNew(){
      $this->layout = false;
      return $this->render('form-new');
    }
    public function actionFormEdit(){
      $this->layout = false;
      $edit = Bank::findOne(Yii::$app->request->get('id'));
      return $this->render('form-edit',[
        'model' => $edit
      ]);
    }
    public function actionDelete(){
      $this->layout = false;
      $id = Yii::$app->request->post('id');
      $bank = Bank::findOne($id);
      $bank->is_delete = 1;
      $bank->save();
    }
    public function actionCreate(){
      if(Yii::$app->request->post('id')){
        $model = Bank::findOne(Yii::$app->request->post('id'));
      }else{
        $model = new Bank();
      }

      $model->name = strip_tags(Yii::$app->request->post('name'));
      $model->rekening_name = strip_tags(Yii::$app->request->post('rekening_name'));
      $model->rekening_number = strip_tags(Yii::$app->request->post('rekening_number'));
      if(isset($_FILES['banner']['name']) and $_FILES['banner']['name'] != ''){
        $file_name = $_FILES['banner']['name'];
        $file_tmp =$_FILES['banner']['tmp_name'];
        $tmp = explode('.', $file_name);
        $file_ext = end($tmp);
        $newfilename = md5(date('Y-m-d H:i:s')) .'.'. $file_ext;

        move_uploaded_file($file_tmp,"media/bank/".$newfilename);
        $model->image = $newfilename;

      }
      $model->save();
    }

}

app/modules/dashboard/views/bank/form-edit.php
<form id="form-bank-edit">
  <input type="hidden" name="id" value="<?= $model->id ?>">
  <div class="form-group">
    <label for="">Bank Name</label>
    <input type="text" class="form-control" name="name" value="<?= $model->name ?>">
  </div>
  <div class="form-group">
    <label for="">Rekening Name</label>
    <input type="text" class="form-control" name="rekening_name" value="<?= $model->rekening_name ?>">
  </div>
  <div class="form-group">
    <label for="">Rekening Number</label>
    <input type="text" class="form-control" name="rekening_number" value="<?= $model->rekening_number ?>">
  </div>
  <div class="form-group">
    <label for="">Logo</label>
    <input type="file" class="setpreview" name="logo" value="">
    <img src="<?= Yii::$app->params['base_url'] . 'media/bank/'. $model->image ?>" alt="" class="getpreview">
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary" name="button">Save</button>
  </div>
</form>
<style media="screen">
  .getpreview{
    width: 70px !important;
    height: auto !important;
    margin-top: 10px
  }
</style>
<script type="text/javascript">
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('.getpreview').attr('src', e.target.result).css('margin-bottom','15px');
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$(".setpreview").change(function(){
    readURL(this);
});
$('#form-bank-edit').validate({
  rules : {
    name : {
      required : true
    },
    rekening_name : {
      required : true
    },
    rekening_number : {
      required : true,
      digits : true
    }
  },
  messages : {
    name : {
      required : 'please fill the name of Bank'
    },
    rekening_name : {
      required : 'please fill the rekening name'
    },
    rekening_number : {
      required : 'please fill the rekening number',
      digits : 'please fill the right value'
    }
  },
  submitHandler : function(form){
    $('#form-bank-edit button').prop('disabled',true).html('saving ...');
    var kuy = $('#form-bank-edit')[0];
    var formData = new FormData(kuy);

    formData.append('banner', $('#form-bank-edit input[type=file]')[0].files[0]);
    formData.append('_csrf', $('#gils').val());

    $.ajax({
      url : base + 'bank/create',
      type : 'POST',
      contentType: false,
      cache: false,
      processData:false,
      data : formData,
      success : function(data){
        window.location = base + 'bank';
      }
    });
    return false;
  }
});
</script>

app/modules/dashboard/views/bank/form-new.php
<form id="form-bank">
  <div class="form-group">
    <label for="">Bank Name</label>
    <input type="text" class="form-control" name="name" value="">
  </div>
  <div class="form-group">
    <label for="">Rekening Name</label>
    <input type="text" class="form-control" name="rekening_name" value="">
  </div>
  <div class="form-group">
    <label for="">Rekening Number</label>
    <input type="text" class="form-control" name="rekening_number" value="">
  </div>
  <div class="form-group">
    <label for="">Logo</label>
    <input type="file" name="logo" value="">
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary" name="button">Save</button>
  </div>
</form>

<script type="text/javascript">
$('#form-bank').validate({
  rules : {
    name : {
      required : true
    },
    rekening_name : {
      required : true
    },
    rekening_number : {
      required : true,
      digits : true
    },
    logo : {
      required : true
    }
  },
  messages : {
    name : {
      required : 'please fill the name of Bank'
    },
    rekening_name : {
      required : 'please fill the rekening name'
    },
    rekening_number : {
      required : 'please fill the rekening number',
      digits : 'please fill the right value'
    },
    logo : {
      required : 'please fill the logo'
    }
  },
  submitHandler : function(form){
    $('#form-bank button').prop('disabled',true).html('saving ...');
    var kuy = $('#form-bank')[0];
    var formData = new FormData(kuy);

    formData.append('banner', $('#form-bank input[type=file]')[0].files[0]);
    formData.append('_csrf', $('#gils').val());

    $.ajax({
      url : base + 'bank/create',
      type : 'POST',
      contentType: false,
      cache: false,
      processData:false,
      data : formData,
      success : function(data){
        window.location = base + 'bank';
      }
    });
    return false;
  }
});
</script>

app/modules/dashboard/views/bank/index.php
<?php

use app\helper\Helper;


/* @var $this yii\web\View */
/* @var $searchModel app\modules\dashboard\models\Search */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Data';
$this->params['breadcrumbs'][] = $this->title;
?>

<div id="content">
  <?= Helper::breadcrumb($breadcrumb); ?>
  <div class="container-fluid">
    <div class="page-index wrapindex">
        <p style="text-align:right"><a id="add-new-bank" href="#" class="btn btn-primary">Add New</a> </p>
        <table id="data-bank">
          <thead>
            <tr>
              <th>#</th>
              <th>Bank</th>
              <th>Rekening Name</th>
              <th>Rekening Number</th>
              <th>Logo</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach($banks as $bank){ ?>
            <tr>
              <td></td>
              <td><?= $bank->name ?></td>
              <td><?= $bank->rekening_name ?></td>
              <td><?= $bank->rekening_number ?></td>
              <td><img src="<?= Yii::$app->params['base_url'].'media/bank/'. $bank->image ?>" width="70"> </td>
              <td>
                <a href="#" class="edit edit-bank" data-id="<?= $bank->id ?>">edit</a>
                <a href="#" class="hapus delete-bank" data-id="<?= $bank->id ?>">delete</a>
              </td>
            </tr>
            <?php } ?>
          </tbody>
        </table>

    </div>

  </div>
</div>